version: 2
jobs:
  build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: pip install nrfutil
      - run: cp Makefile.posix Code/3rd/nrf5_sdk/nRF5_SDK_12.1.0_0d23e2a/components/toolchain/gcc/Makefile.posix
      - run:
          name: build
          command: make -C Code/Firmware/shapp
      - run:
          name: Print the Current Time
          command: date